# Generated by Django 5.0.1 on 2024-03-01 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('movieDesc', models.TextField(max_length=1200)),
                ('movieGenre', models.PositiveIntegerField(default=0)),
                ('movieCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movieTime', models.CharField(choices=[('11:30 am', '11:30 am'), ('2:30 pm', '2:30 pm'), ('5:00 pm', '5:00 pm'), ('9:00 pm', '9:00 pm')], max_length=10)),
                ('movieFromDate', models.DateField()),
                ('movieEndDate', models.DateField(default=datetime.datetime(2024, 3, 31, 8, 20, 12, 212196))),
            ],
        ),
    ]
