# Generated by Django 5.0.1 on 2024-03-05 22:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('movieDesc', models.TextField(max_length=1200)),
                ('movieGenre', models.TextField(max_length=200)),
                ('movieCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movieTime', models.CharField(choices=[('11:30 am', '11:30 am'), ('2:30 pm', '2:30 pm'), ('5:00 pm', '5:00 pm'), ('9:00 pm', '9:00 pm')], max_length=10)),
                ('movieFromDate', models.DateField()),
                ('movieEndDate', models.DateField(default=datetime.datetime(2024, 4, 5, 4, 13, 16, 86357))),
            ],
        ),
        migrations.CreateModel(
            name='BookingRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateField()),
                ('bookingTime', models.CharField(max_length=10)),
                ('noOfBookings', models.PositiveIntegerField()),
                ('seatNumbers', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHub.movie')),
            ],
        ),
    ]
