# Generated by Django 5.0.1 on 2024-03-02 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHub', '0002_alter_movie_movieenddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieEndDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 1, 22, 26, 46, 162987)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieGenre',
            field=models.TextField(max_length=200),
        ),
    ]
