# Generated by Django 5.0.1 on 2024-03-07 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHub', '0002_bookingregister_bookingqr_alter_movie_movieenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingregister',
            name='bookingPDF',
            field=models.FileField(blank=True, null=True, upload_to='booking_pdfs/'),
        ),
        migrations.AlterField(
            model_name='bookingregister',
            name='bookingQR',
            field=models.FileField(blank=True, null=True, upload_to='booking_qr/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieEndDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 6, 9, 42, 36, 427348)),
        ),
    ]
