# Generated by Django 5.0.1 on 2024-03-05 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHub', '0004_alter_movie_movieenddate_bookingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieEndDate',
            field=models.DateField(default=datetime.datetime(2024, 4, 4, 19, 3, 12, 797191)),
        ),
    ]
