# Generated by Django 5.0.1 on 2024-03-05 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHub', '0006_alter_movie_movieenddate_bookingrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrecord',
            name='bookingTime',
            field=models.CharField(max_length=10),
        ),
    ]
